version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: comp3123_assignment2
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_CONNECTION_STRING: 'mongodb+srv://paolocasison:abc.123@cluster0.3myz13n.mongodb.net/comp3123_assignment1?retryWrites=true&w=majority'
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


volumes:
  data:
  logs:
