version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Assignment2

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DB_CONNECTION_STRING: "mongodb+srv://paolocasison:abc.123@cluster0.3myz13n.mongodb.net/Assignment2?retryWrites=true&w=majority"

  frontend:
    build:
      context: ./frontend
    ports:
      -  "3001:80"
    depends_on:
      - backend